# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: "ru-RU"
reviews:
  profile: chill
  high_level_summary: true
  review_status: true
  auto_review:
    enabled: true
    drafts: false
    auto_incremental_review: true
