import { defaultOptions } from '../model/options.js'

/**
 * JSON Schema describing the configurable options exposed in the options UI.
 * The schema is intentionally limited to Draft-07 features we actively support
 * in the renderer as well as a small set of custom keywords declared in
 * validation.js.
 */
export const optionsSchema = {
  $id: 'https://github.com/Fannon/search-bookmarks-history-and-tabs/options-schema.json',
  $schema: 'http://json-schema.org/draft-07/schema#',
  type: 'object',
  additionalProperties: false,
  properties: {
    debug: {
      'type': 'boolean',
      'default': defaultOptions.debug,
      'description': 'Log additional diagnostic information to help troubleshooting.',
      'x-ui-section': 'general',
    },
    searchStrategy: {
      'type': 'string',
      'enum': ['precise', 'fuzzy'],
      'default': defaultOptions.searchStrategy,
      'description': 'Search approach to use for matching.',
      'x-ui-section': 'search',
    },
    searchMaxResults: {
      'type': 'integer',
      'minimum': 1,
      'default': defaultOptions.searchMaxResults,
      'description': 'Maximum number of search results to display.',
      'x-ui-section': 'search',
    },
    searchMinMatchCharLength: {
      'type': 'integer',
      'minimum': 1,
      'default': defaultOptions.searchMinMatchCharLength,
      'description': 'Minimum length of the search term considered for a match.',
      'x-ui-section': 'search',
    },
    searchFuzzyness: {
      'type': 'number',
      'minimum': 0,
      'maximum': 1,
      'default': defaultOptions.searchFuzzyness,
      'description': 'Fuzzy search threshold between 0 (precise) and 1 (full fuzziness).',
      'x-ui-section': 'search',
    },
    searchDebounceMs: {
      'type': 'integer',
      'minimum': 0,
      'default': defaultOptions.searchDebounceMs,
      'description': 'Debounce duration for the search field in milliseconds.',
      'x-ui-section': 'search',
    },
    colorStripeWidth: {
      'type': 'integer',
      'minimum': 0,
      'maximum': 16,
      'default': defaultOptions.colorStripeWidth,
      'description': 'Width of the accent stripe next to search results in pixels.',
      'x-ui-section': 'style',
    },
    bookmarkColor: {
      'type': 'string',
      'pattern': '^#([0-9a-fA-F]{3}){1,2}$',
      'default': defaultOptions.bookmarkColor,
      'description': 'Color used for bookmark results.',
      'x-ui-section': 'style',
    },
    tabColor: {
      'type': 'string',
      'pattern': '^#([0-9a-fA-F]{3}){1,2}$',
      'default': defaultOptions.tabColor,
      'description': 'Color used for tab results.',
      'x-ui-section': 'style',
    },
    historyColor: {
      'type': 'string',
      'pattern': '^#([0-9a-fA-F]{3}){1,2}$',
      'default': defaultOptions.historyColor,
      'description': 'Color used for history results.',
      'x-ui-section': 'style',
    },
    searchColor: {
      'type': 'string',
      'pattern': '^#([0-9a-fA-F]{3}){1,2}$',
      'default': defaultOptions.searchColor,
      'description': 'Color used for built-in search engines.',
      'x-ui-section': 'style',
    },
    customSearchColor: {
      'type': 'string',
      'pattern': '^#([0-9a-fA-F]{3}){1,2}$',
      'default': defaultOptions.customSearchColor,
      'description': 'Color used for custom search engines.',
      'x-ui-section': 'style',
    },
    directColor: {
      'type': 'string',
      'pattern': '^#([0-9a-fA-F]{3}){1,2}$',
      'default': defaultOptions.directColor,
      'description': 'Color used for direct URL matches.',
      'x-ui-section': 'style',
    },
    enableTabs: {
      'type': 'boolean',
      'default': defaultOptions.enableTabs,
      'description': 'Index and search open tabs.',
      'x-ui-section': 'sources',
    },
    enableBookmarks: {
      'type': 'boolean',
      'default': defaultOptions.enableBookmarks,
      'description': 'Index and search bookmarks.',
      'x-ui-section': 'sources',
    },
    enableHistory: {
      'type': 'boolean',
      'default': defaultOptions.enableHistory,
      'description': 'Index and search browser history.',
      'x-ui-section': 'sources',
    },
    enableSearchEngines: {
      'type': 'boolean',
      'default': defaultOptions.enableSearchEngines,
      'description': 'Show search engine links for fallback searches.',
      'x-ui-section': 'sources',
    },
    enableHelp: {
      'type': 'boolean',
      'default': defaultOptions.enableHelp,
      'description': 'Display tips when the popup loads.',
      'x-ui-section': 'sources',
    },
    enableDirectUrl: {
      'type': 'boolean',
      'default': defaultOptions.enableDirectUrl,
      'description': 'Recognize typed URLs and allow direct navigation.',
      'x-ui-section': 'sources',
    },
    displayTags: {
      'type': 'boolean',
      'default': defaultOptions.displayTags,
      'description': 'Show and search bookmark tags.',
      'x-ui-section': 'display',
    },
    displayFolderName: {
      'type': 'boolean',
      'default': defaultOptions.displayFolderName,
      'description': 'Show bookmark folder names in results.',
      'x-ui-section': 'display',
    },
    displaySearchMatchHighlight: {
      'type': 'boolean',
      'default': defaultOptions.displaySearchMatchHighlight,
      'description': 'Highlight matches within results.',
      'x-ui-section': 'display',
    },
    displayLastVisit: {
      'type': 'boolean',
      'default': defaultOptions.displayLastVisit,
      'description': 'Display relative time since the last visit.',
      'x-ui-section': 'display',
    },
    displayVisitCounter: {
      'type': 'boolean',
      'default': defaultOptions.displayVisitCounter,
      'description': 'Display how often an item was visited.',
      'x-ui-section': 'display',
    },
    displayDateAdded: {
      'type': 'boolean',
      'default': defaultOptions.displayDateAdded,
      'description': 'Display the creation date for bookmarks.',
      'x-ui-section': 'display',
    },
    displayScore: {
      'type': 'boolean',
      'default': defaultOptions.displayScore,
      'description': 'Display the calculated score next to each result.',
      'x-ui-section': 'display',
    },
    bookmarksIgnoreFolderList: {
      'type': 'array',
      'items': {
        type: 'string',
        minLength: 1,
      },
      'default': defaultOptions.bookmarksIgnoreFolderList,
      'description': 'Folders whose bookmarks should be excluded from search.',
      'x-ui-section': 'bookmarks',
    },
    tabsOnlyCurrentWindow: {
      'type': 'boolean',
      'default': defaultOptions.tabsOnlyCurrentWindow,
      'description': 'Limit tab indexing to the current browser window.',
      'x-ui-section': 'tabs',
    },
    maxRecentTabsToShow: {
      'type': 'integer',
      'minimum': 0,
      'default': defaultOptions.maxRecentTabsToShow,
      'description': 'Number of recent tabs shown when opening the popup without a query.',
      'x-ui-section': 'tabs',
      'x-allowZeroOrMin': 3,
    },
    historyDaysAgo: {
      'type': 'integer',
      'minimum': 1,
      'default': defaultOptions.historyDaysAgo,
      'description': 'How many days of history to include.',
      'x-ui-section': 'history',
    },
    historyMaxItems: {
      'type': 'integer',
      'minimum': 0,
      'default': defaultOptions.historyMaxItems,
      'description': 'Maximum number of history entries to index.',
      'x-ui-section': 'history',
    },
    historyIgnoreList: {
      'type': 'array',
      'items': {
        type: 'string',
        minLength: 1,
      },
      'default': defaultOptions.historyIgnoreList,
      'description': 'URLs containing these fragments will be skipped from history results.',
      'x-ui-section': 'history',
    },
    searchEngineChoices: {
      'type': 'array',
      'minItems': 1,
      'items': {
        $ref: '#/definitions/searchEngine',
      },
      'default': defaultOptions.searchEngineChoices,
      'description': 'Built-in search engines offered as fallback entries.',
      'x-ui-section': 'searchEngines',
    },
    customSearchEngines: {
      'type': 'array',
      'items': {
        $ref: '#/definitions/customSearchEngine',
      },
      'default': defaultOptions.customSearchEngines,
      'description': 'Custom search engines with optional aliases and blank URLs.',
      'x-ui-section': 'searchEngines',
    },
    scoreMinScore: {
      'type': 'integer',
      'minimum': 0,
      'default': defaultOptions.scoreMinScore,
      'description': 'Filter out results scoring below this threshold.',
      'x-ui-section': 'scores',
    },
    scoreMinSearchTermMatchRatio: {
      'type': 'number',
      'minimum': 0,
      'maximum': 1,
      'default': defaultOptions.scoreMinSearchTermMatchRatio,
      'description': 'Required match ratio for precise search.',
      'x-ui-section': 'scores',
    },
    scoreBookmarkBaseScore: {
      'type': 'integer',
      'default': defaultOptions.scoreBookmarkBaseScore,
      'description': 'Base score applied to bookmark results.',
      'x-ui-section': 'scores',
    },
    scoreTabBaseScore: {
      'type': 'integer',
      'default': defaultOptions.scoreTabBaseScore,
      'description': 'Base score applied to open tab results.',
      'x-ui-section': 'scores',
    },
    scoreHistoryBaseScore: {
      'type': 'integer',
      'default': defaultOptions.scoreHistoryBaseScore,
      'description': 'Base score applied to history results.',
      'x-ui-section': 'scores',
    },
    scoreSearchEngineBaseScore: {
      'type': 'integer',
      'default': defaultOptions.scoreSearchEngineBaseScore,
      'description': 'Base score applied to default search engines.',
      'x-ui-section': 'scores',
    },
    scoreCustomSearchEngineBaseScore: {
      'type': 'integer',
      'default': defaultOptions.scoreCustomSearchEngineBaseScore,
      'description': 'Base score applied to custom search engines.',
      'x-ui-section': 'scores',
    },
    scoreDirectUrlScore: {
      'type': 'integer',
      'default': defaultOptions.scoreDirectUrlScore,
      'description': 'Base score applied when typing a direct URL.',
      'x-ui-section': 'scores',
    },
    scoreTitleWeight: {
      'type': 'number',
      'default': defaultOptions.scoreTitleWeight,
      'description': 'Weight multiplier for matches in titles.',
      'x-ui-section': 'scores',
    },
    scoreTagWeight: {
      'type': 'number',
      'default': defaultOptions.scoreTagWeight,
      'description': 'Weight multiplier for matches in tags.',
      'x-ui-section': 'scores',
    },
    scoreUrlWeight: {
      'type': 'number',
      'default': defaultOptions.scoreUrlWeight,
      'description': 'Weight multiplier for matches in URLs.',
      'x-ui-section': 'scores',
    },
    scoreFolderWeight: {
      'type': 'number',
      'default': defaultOptions.scoreFolderWeight,
      'description': 'Weight multiplier for matches in folder names.',
      'x-ui-section': 'scores',
    },
    scoreCustomBonusScore: {
      'type': 'boolean',
      'default': defaultOptions.scoreCustomBonusScore,
      'description': 'Allow bookmark titles to embed manual bonus scores.',
      'x-ui-section': 'scores',
    },
    scoreExactIncludesBonus: {
      'type': 'integer',
      'default': defaultOptions.scoreExactIncludesBonus,
      'description': 'Bonus score for exact include matches.',
      'x-ui-section': 'scores',
    },
    scoreExactIncludesBonusMinChars: {
      'type': 'integer',
      'minimum': 1,
      'default': defaultOptions.scoreExactIncludesBonusMinChars,
      'description': 'Minimum characters needed for exact include bonus.',
      'x-ui-section': 'scores',
    },
    scoreExactStartsWithBonus: {
      'type': 'integer',
      'default': defaultOptions.scoreExactStartsWithBonus,
      'description': 'Bonus score when title or URL starts with the search term.',
      'x-ui-section': 'scores',
    },
    scoreExactEqualsBonus: {
      'type': 'integer',
      'default': defaultOptions.scoreExactEqualsBonus,
      'description': 'Bonus score when title matches exactly.',
      'x-ui-section': 'scores',
    },
    scoreExactTagMatchBonus: {
      'type': 'integer',
      'default': defaultOptions.scoreExactTagMatchBonus,
      'description': 'Bonus score for exact tag matches.',
      'x-ui-section': 'scores',
    },
    scoreExactFolderMatchBonus: {
      'type': 'integer',
      'default': defaultOptions.scoreExactFolderMatchBonus,
      'description': 'Bonus score for exact folder matches.',
      'x-ui-section': 'scores',
    },
    scoreVisitedBonusScore: {
      'type': 'number',
      'minimum': 0,
      'default': defaultOptions.scoreVisitedBonusScore,
      'description': 'Bonus score per visit from browsing history.',
      'x-ui-section': 'scores',
    },
    scoreVisitedBonusScoreMaximum: {
      'type': 'integer',
      'minimum': 0,
      'default': defaultOptions.scoreVisitedBonusScoreMaximum,
      'description': 'Upper bound for visit-based bonus score.',
      'x-ui-section': 'scores',
    },
    scoreRecentBonusScoreMaximum: {
      'type': 'integer',
      'minimum': 0,
      'default': defaultOptions.scoreRecentBonusScoreMaximum,
      'description': 'Maximum bonus for recently visited items.',
      'x-ui-section': 'scores',
    },
    titleLengthRestrictionForUrls: {
      'type': 'integer',
      'minimum': 0,
      'default': defaultOptions.titleLengthRestrictionForUrls,
      'description': 'Maximum URL length before shortening titles.',
      'x-ui-section': 'powerUsers',
    },
    uFuzzyOptions: {
      'type': 'object',
      'default': defaultOptions.uFuzzyOptions,
      'description': 'Advanced configuration for the uFuzzy search library.',
      'additionalProperties': true,
      'x-ui-section': 'powerUsers',
    },
  },
  definitions: {
    searchEngine: {
      type: 'object',
      required: ['name', 'urlPrefix'],
      additionalProperties: false,
      properties: {
        name: {
          type: 'string',
          minLength: 1,
        },
        urlPrefix: {
          type: 'string',
          minLength: 1,
        },
      },
    },
    customSearchEngine: {
      type: 'object',
      required: ['alias', 'name', 'urlPrefix'],
      additionalProperties: false,
      properties: {
        alias: {
          oneOf: [
            {
              type: 'array',
              minItems: 1,
              items: {
                type: 'string',
                minLength: 1,
              },
            },
            {
              type: 'string',
              minLength: 1,
            },
          ],
        },
        name: {
          type: 'string',
          minLength: 1,
        },
        urlPrefix: {
          type: 'string',
          minLength: 1,
        },
        blank: {
          type: 'string',
          minLength: 1,
        },
      },
    },
  },
}

export const uiSchema = {
  sectionOrder: [
    'general',
    'search',
    'style',
    'sources',
    'display',
    'bookmarks',
    'tabs',
    'history',
    'searchEngines',
    'scores',
    'powerUsers',
  ],
  sections: {
    general: {
      title: 'General',
      description: 'Configure extension wide behaviour.',
    },
    search: {
      title: 'Search',
      description: 'Tune core search behaviour and responsiveness.',
    },
    style: {
      title: 'Style',
      description: 'Customize colors and visual accents.',
    },
    sources: {
      title: 'Sources',
      description: 'Enable or disable data sources.',
    },
    display: {
      title: 'Display',
      description: 'Control which metadata is rendered for each result.',
    },
    bookmarks: {
      title: 'Bookmarks',
      description: 'Fine tune bookmark indexing.',
    },
    tabs: {
      title: 'Tabs',
      description: 'Control how open tabs are handled.',
    },
    history: {
      title: 'History',
      description: 'Adjust browser history indexing.',
    },
    searchEngines: {
      title: 'Search Engines',
      description: 'Curate built-in and custom search engine shortcuts.',
    },
    scores: {
      title: 'Scores',
      description: 'Modify scoring heuristics.',
    },
    powerUsers: {
      title: 'Power Users',
      description: 'Advanced options for experienced users.',
      collapsedByDefault: true,
    },
  },
  fields: {
    'debug': { control: 'switch' },
    'searchStrategy': {
      control: 'segmented',
      options: [
        { value: 'precise', label: 'Precise' },
        { value: 'fuzzy', label: 'Fuzzy' },
      ],
    },
    'searchMaxResults': { control: 'number', unit: 'results', step: 1 },
    'searchMinMatchCharLength': { control: 'number', step: 1 },
    'searchFuzzyness': { control: 'slider', step: 0.05 },
    'searchDebounceMs': { control: 'number', unit: 'ms', step: 10 },
    'colorStripeWidth': { control: 'number', unit: 'px', step: 1 },
    'bookmarkColor': { control: 'color' },
    'tabColor': { control: 'color' },
    'historyColor': { control: 'color' },
    'searchColor': { control: 'color' },
    'customSearchColor': { control: 'color' },
    'directColor': { control: 'color' },
    'enableTabs': { control: 'switch' },
    'enableBookmarks': { control: 'switch' },
    'enableHistory': { control: 'switch' },
    'enableSearchEngines': { control: 'switch' },
    'enableHelp': { control: 'switch' },
    'enableDirectUrl': { control: 'switch' },
    'displayTags': { control: 'switch' },
    'displayFolderName': { control: 'switch' },
    'displaySearchMatchHighlight': { control: 'switch' },
    'displayLastVisit': { control: 'switch' },
    'displayVisitCounter': { control: 'switch' },
    'displayDateAdded': { control: 'switch' },
    'displayScore': { control: 'switch' },
    'bookmarksIgnoreFolderList': { control: 'stringList', placeholder: 'Folder name' },
    'tabsOnlyCurrentWindow': { control: 'switch' },
    'maxRecentTabsToShow': { control: 'number', step: 1 },
    'historyDaysAgo': { control: 'number', step: 1, unit: 'days' },
    'historyMaxItems': { control: 'number', step: 32 },
    'historyIgnoreList': { control: 'stringList', placeholder: 'URL fragment' },
    'searchEngineChoices': { control: 'objectList', itemName: 'Search Engine' },
    'customSearchEngines': { control: 'objectList', itemName: 'Custom Search Engine' },
    'scoreMinScore': { control: 'number', step: 1 },
    'scoreMinSearchTermMatchRatio': { control: 'slider', step: 0.05 },
    'scoreBookmarkBaseScore': { control: 'number', step: 1 },
    'scoreTabBaseScore': { control: 'number', step: 1 },
    'scoreHistoryBaseScore': { control: 'number', step: 1 },
    'scoreSearchEngineBaseScore': { control: 'number', step: 1 },
    'scoreCustomSearchEngineBaseScore': { control: 'number', step: 1 },
    'scoreDirectUrlScore': { control: 'number', step: 1 },
    'scoreTitleWeight': { control: 'number', step: 0.1 },
    'scoreTagWeight': { control: 'number', step: 0.1 },
    'scoreUrlWeight': { control: 'number', step: 0.1 },
    'scoreFolderWeight': { control: 'number', step: 0.1 },
    'scoreCustomBonusScore': { control: 'switch' },
    'scoreExactIncludesBonus': { control: 'number', step: 1 },
    'scoreExactIncludesBonusMinChars': { control: 'number', step: 1 },
    'scoreExactStartsWithBonus': { control: 'number', step: 1 },
    'scoreExactEqualsBonus': { control: 'number', step: 1 },
    'scoreExactTagMatchBonus': { control: 'number', step: 1 },
    'scoreExactFolderMatchBonus': { control: 'number', step: 1 },
    'scoreVisitedBonusScore': { control: 'number', step: 0.1 },
    'scoreVisitedBonusScoreMaximum': { control: 'number', step: 1 },
    'scoreRecentBonusScoreMaximum': { control: 'number', step: 1 },
    'titleLengthRestrictionForUrls': { control: 'number', step: 5 },
    'uFuzzyOptions': { control: 'json', advanced: true },
    'searchEngineChoices[].name': { label: 'Name' },
    'searchEngineChoices[].urlPrefix': { label: 'URL Prefix' },
    'customSearchEngines[].alias': { control: 'stringList', label: 'Aliases' },
    'customSearchEngines[].name': { label: 'Name' },
    'customSearchEngines[].urlPrefix': { label: 'URL Prefix' },
    'customSearchEngines[].blank': { label: 'Blank (optional)' },
  },
}
